runtime: nodejs18 # or a compatible version like nodejs14
env: standard
service: azfrontend
handlers:
- url: /
  static_files: angularapp/index.html
  upload: angularapp/index.html

- url: /(.*)
  static_files: angularapp/\1
  upload: angularapp/(.*)

# Optional: Set a default expiration time for static assets to improve performance.
# default_expiration: "7d"
