runtime: nodejs18 # or a compatible version like nodejs14
env: standard
service: azfrontend
handlers:
  - url: /
    static_files: dist/angularapp/index.html
    upload: dist/angularapp/index.html
  - url: /
    static_dir: dist/angularapp
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
