runtime: nodejs16 # or a compatible version like nodejs14
env: standard
service: azfrontend
handlers:
- url: /
  static_files: dist/angularapp/index.html
  upload: dist/angularapp/index.html

- url: /(.*)
  static_files: dist/angularapp/\1
  upload: dist/angularapp/(.*)

# Optional: Set a default expiration time for static assets to improve performance.
# default_expiration: "7d"